# Generated by Django 5.0.2 on 2024-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_instructor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='url',
            new_name='cv',
        ),
        migrations.AddField(
            model_name='instructor',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(null=True),
        ),
    ]
